In [6]:
import requests

In [19]:
URL = "https://stephen-king-api.onrender.com/api/books"

ris = requests.get(URL)

print(res)

json_data = res.json()

<Response [200]>

In [29]:
import pandas as pd

df = pd.json_normalize(json_data["data"])
df = df[['id', 'Title', 'Year','ISBN']]

In [30]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [47]:

URL2 = "https://cataas.com/api/tags"

dat = requests.get(URL2)

data = dat.json()

data

['',
 '#christmascat',
 '#scottishfold',
 '.',
 '2cats',
 '4',
 '62',
 '@Beardlyness',
 'A',
 'Angry',
 'B&W',
 'Baby',
 'Bed',
 'Beer',
 'Belfast',
 'BelfastMet',
 'Bengal',
 'Bester',
 'BigEar',
 'BigEars',
 'Black',
 'Black Scotish Cute',
 'Black and white',
 'Black cat',
 'BlackInWhite',
 'Blackcat',
 'Boba',
 'Bobo',
 'Box',
 'British',
 'Buckley',
 'Cat',
 'Cat in a faucet',
 'Cat surfing the tube',
 'Catto',
 'Chair',
 'Chocolate',
 'Christmas',
 'Christmas 🎄',
 'ColdCat',
 'Collar',
 'CryptoWorld Cat',
 'Cubbas',
 'Cubbers',
 'Cubbs',
 'Cubby',
 'Curious',
 'Cute',
 'Daiki',
 'Dark',
 'Evil',
 'FAT',
 'Fat',
 'Female',
 'Ferris',
 'Fierce',
 'Fluffy',
 'Friends',
 'Fulgencio',
 'Funny',
 'Going shopping?',
 'Gray',
 'GreenEyes',
 'Grey',
 'Grumpy',
 'Gustav',
 'Halloween',
 'HandInHand',
 'Happy',
 'Hemingway',
 'Hidden',
 'Hides',
 'Hiding',
 'Hitler',
 'Hugs',
 'If-fits-I-sits',
 'Julijana',
 'KingCat',
 'KitKat',
 'Kitten',
 'Lay',
 'Long',
 'Luz',
 'Maine Coon',
 'Maine coon',
 'Male',
 'Maskcat',
 'Meme',
 'Mimi',
 'Moomoo',
 'My cat(Mamay(мамай)) bebrik.xyz',
 'NSFW',
 'Nazi',
 'New Year',
 'NorthenCat',
 'Norwegian',
 'Norwegian Forest Cat',
 'OG',
 'OnTheNotebook',
 'Orange',
 'Oreo',
 'Oriental',
 'Outside',
 'Peekaboo',
 'Polysson',
 'PopcornTrap',
 'Quantico',
 'Ragdoll',
 'Relaxed',
 'Rex',
 'Roar',
 'SWS',
 'Sad',
 'Scout',
 'Screaming',
 'Shhhsh',
 'Shi',
 'Shiloh',
 'Shoes',
 'Siamese',
 'Sigma Ohio cat very skibidi',
 'Silly',
 'Sillykitty',
 'Simba',
 'Sink',
 'Sleep',
 'Sleeping',
 'Sleepy',
 'Smol',
 'Sniper',
 'Spots',
 'Steve jobs',
 'Summer',
 'Tabby',
 'Tabby  cute',
 'Tabbycat',
 'Tassilo',
 'Teeth',
 'Tent',
 'Tired cat',
 'TorWorld Cat',
 'Torte',
 'Torte Tabby',
 'Trippy',
 'Tuxedo',
 'TwoCats',
 'Village',
 'VoIP',
 'Wafer',
 'Waif',
 'Waits',
 'Weegie',
 'Wet',
 'White',
 'Wide',
 'Wide mouth',
 'X-MAS',
 'Yeet',
 'Zathras',
 'Zoomies',
 'a',
 'achievement',
 'acq',
 'action',
 'adult',
 'advent-calendar-2016',
 'afraid',
 'air_bed',
 'airpods',
 'alarming',
 'alcoholic',
 'aldris',
 'algebra',
 'alien',
 'ange',
 'angel',
 'angry',
 'angry cat',
 'annilou91',
 'annoyed',
 'anoyed',
 'anstrengend',
 'apple',
 'approaching',
 'arm',
 'arrogant',
 'art',
 'artist',
 'asking',
 'asleep',
 'attack',
 'attention',
 'attentive',
 'attitude',
 'ava',
 'avatar',
 'awake',
 'babby',
 'baby',
 'babycat',
 'back',
 'background',
 'backpack',
 'bad_photoshop',
 'baker',
 'baking',
 'ball',
 'bamgu',
 'bang',
 'banker',
 'banzai',
 'basin',
 'basket',
 'bath',
 'beautiful',
 'bed',
 'beer',
 'beg',
 'begging',
 'bella',
 'belly',
 'belly rubs',
 'bengal',
 'bent',
 'berlin',
 'best',
 'bestcat',
 'big',
 'big eyes',
 'big floof',
 'big-eyes',
 'bigfloppa',
 'binky',
 'bird',
 'birthday',
 'biscuit',
 'bitting',
 'black',
 'black & white',
 'black an white',
 'black and white',
 'black cat',
 'black scotish',
 'blackandwhite',
 'blanket',
 'blep',
 'blini',
 'blink',
 'blonde',
 'blue',
 'blue eyes',
 'blueeyes',
 'blur',
 'blurred',
 'blurry',
 'bobba eyes',
 'boi',
 'bombay',
 'bonus dog',
 'boop',
 'boot',
 'bored',
 'bossy',
 'boty',
 'bow',
 'box',
 'boxe',
 'brasileira',
 'brazilian',
 'brazilian cat',
 'bread',
 'breast',
 'british',
 'british shorthair',
 'british-shorthair',
 'broken',
 'brothers',
 'brown',
 'bubble',
 'bucket',
 'bun',
 'bunny',
 'burnt',
 'burrito',
 'burrito-cat',
 'business',
 'buubly',
 'bw',
 'cables',
 'cake',
 'calico',
 'calvin',
 'camera',
 'candle',
 'candy corn',
 'car',
 'caracal',
 'carrier',
 'carrot',
 'cars',
 'cartoon',
 'cash',
 'cat',
 'cat eyes',
 'cat face',
 'cat kneading',
 'cat meowing',
 'cat n frog',
 'cat on table',
 'cat wallpaper',
 'cat1',
 'cat_winston',
 'catcooking',
 'cats',
 'catstickerss',
 'catto',
 'caughtsnacking',
 'ceiling',
 'chair',
 'chaos',
 'check',
 'chicken',
 'chill',
 'chipi',
 'chocked',
 'chonker',
 'christmas',
 'chunky',
 'cinnamon roll',
 'circle',
 'clangen',
 'clawing',
 'cleaning',
 'climb',
 'close',
 'close-up',
 'closed',
 'closed eyes',
 'closeup',
 'clothes',
 'coat',
 'color',
 'colorful',
 'comfy',
 'computer',
 'confident',
 'confused',
 'console',
 'content',
 'cook',
 'cooking',
 'cool',
 'costume',
 'couch',
 'couple',
 'cow',
 'cowboy',
 'cozy',
 'crazy',
 'crazy russian pussycat',
 'cream',
 'creation',
 'creep',
 'crown',
 'cry',
 'crying',
 'cryptid',
 'cucumber',
 'cuddle',
 'cuddles',
 'cup',
 'curl',
 'curled',
 'curled up',
 'cut',
 'cute',
 'cute cat',
 'cutie',
 'daisy',
 'dance',
 'dancing',
 'dark',
 'dark brown',
 'dark vador',
 'darth',
 'darth vader',
 'dash',
 'davie412',
 'days',
 'dead',
 'decorating',
 'deflate',
 'depressed',
 'derp',
 'desk',
 'detective',
 'dev',
 'devcat',
 'devonrex',
 'devops',
 'dickface',
 'dictator',
 'didizin',
 'dinner!',
 'disappointed',
 'displeased',
 'dissatisfied',
 'distraction',
 'dj',
 'dnd',
 'dog',
 'dogstyle',
 'domini domino',
 'donna',
 'dot',
 'double',
 'down',
 'dozing',
 'dragon-li',
 'draw',
 'dream',
 'dress',
 'drink',
 'drone',
 'drool',
 'drugs',
 'drunk',
 'dumb',
 'dummy',
 'duo',
 'ear',
 'ears',
 'ears back',
 'eepy',
 'elderly',
 'elegant',
 'engineer',
 'evil',
 'excited',
 'exferal',
 'eye',
 'eyes',
 'eyes closed',
 'face',
 'facecat',
 'fail',
 'fall',
 'fancy',
 'fangs',
 'farted',
 'fat',
 'fat cat',
 'fatass',
 'fatfatpankocat',
 'faucet',
 'fedora',
 'feeding',
 'feet',
 'feline',
 'felix',
 'fell',
 'female',
 'female cat',
 'feral',
 'ferrero',
 'festive',
 'fight',
 'fighter',
 'file',
 'fire',
 'fisheye',
 'fist',
 'fit',
 'flat-faced',
 'floof',
 'floor',
 'flop',
 'floppa',
 'flower',
 'flowers',
 'fluffy',
 'fluffy pussy',
 'flying',
 'focused',
 'fold',
 'food',
 'food dish',
 'forest cat',
 'fotel',
 'fragile',
 'freeze',
 'fridge',
 'friends',
 'front_view',
 'fucker',
 'fun',
 'funn',
 'funny',
 'funny kitty',
 'furious',
 'furry',
 'gamer',
 'gaming',
 'ganmo',
 'garfield',
 'gas station',
 'gg',
 'gif',
 'ginger',
 'ginger cat',
 'girl',
 'glaring',
 'glass',
 'glassbreaker',
 'glow',
 'goober',
 'goodness_gracious',
 'goofy',
 'graceful',
 'grass',
 'gray',
 'greedy',
 'green',
 'green eyes',
 'gremlin',
 'grey',
 'grooming',
 'group',
 'grump',
 'grumpy',
 'guard',
 'guardian',
 'guilty',
 'gun',
 'gutter',
 'haha',
 'hairless',
 'halloween',
 'hammock',
 'hand',
 'handicapped',
 'handsome',
 'hangover',
 'happy',
 'hard',
 'harness',
 'hash_brown',
 'hat',
 'haunting',
 'hawaii',
 'head',
 'head tilt',
 'headinacup',
 'headphones',
 'heart',
 'hedgehog',
 'hehe',
 'held',
 'hello',
 'helpful',
 'hernan',
 'heterochromia',
 'hi',
 'hide',
 'hiding',
 'high_quality',
 'highway_hoop',
 'hilter',
 'himalayan',
 'hissing',
 'ho',
 'ho-wait',
 'hold',
 'holding',
 'holiday',
 'horror',
 'hot',
 'housemaid',
 'housepanther',
 'hovercat',
 'hug',
 'huge',
 'huh',
 'hulu',
 'human',
 'hunger',
 'hungry',
 'icecream',
 'idiotic',
 'if i fits i sits',
 'interesting',
 'interrupted',
 'italian st',
 'itsatrap',
 'ivy',
 'jacket',
 'jade',
 'jellybean toes toe beans grey gray mauve',
 'jellybean toes toebeans squished beans',
 'jinx',
 'jojo',
 'judgemental',
 'judging',
 'judgy',
 'julijana',
 'jump',
 'jumping',
 'kamilo',
 'keyboard',
 'kick',
 'kinky pussy',
 'kiss',
 'kitchencat',
 'kitler',
 'kitten',
 'kittenleg',
 'kittens',
 'kitty',
 'kittypet',
 'knocknoc',
 'kot',
 'kucing',
 'kuro',
 'lan',
 'lap',
 'laptop',
 'large',
 'lasagna',
 'lashes',
 'laugh',
 'laughing',
 'lay',
 'laying',
 'lazy',
 'lazy fuck',
 'leg',
 'legs',
 'lemonade',
 'lick',
 'licking',
 'lights',
 'like a boss',
 'lil',
 'lila',
 'lily',
 'linux',
 'lion',
 'littermates',
 'little',
 'loaf',
 'logan',
 'lol',
 'lolcat',
 'londrina',
 'londrinense',
 'long',
 'long hair',
 'long-cat',
 'long-hair',
 'long-haired',
 'longhair',
 'longhaired',
 'look',
 'looker',
 'looking',
 'looking at viewer',
 'looking away',
 'loopy',
 'lost',
 'lounge',
 'lounging',
 'love',
 'lovely',
 'low quality',
 'lowres',
 'luna',
 'lustful',
 'lying',
 'lying down',
 'lying-down',
 'lying-on-laptop',
 'lynxpoint',
 'macCat',
 'mackerel tabby',
 'mad',
 'magnifier',
 'magnifying glass',
 'maine',
 'maine coon',
 'maine-coon',
 'mainecoon',
 'male',
 'mama',
 'manspreading',
 'many',
 'marin',
 'marine',
 'mask',
 'massage',
 'mcdonalds',
 'mean',
 'meditating',
 'medium hair',
 'meet',
 'melon',
 'meme',
 'menacing',
 'meow',
 'messy',
 'metal',
 'mew',
 'mexican',
 'misty',
 'mix',
 'mixed',
 'mlem',
 'money',
 'moody',
 'morrigan',
 'morrigan witch of the wilds',
 'motion blur',
 'mouse',
 'mousecat',
 'mouth',
 'movement',
 'multi',
 'multicolored',
 'multiple',
 'multiple_colors',
 'munchkin',
 'murzik',
 'mustache',
 'müde',
 'nader',
 'nails',
 'nap',
 'nasty',
 'nature',
 'near',
 'needy',
 'nelly',
 'nelut',
 'network',
 'new year',
 'newyear',
 'nicecat',
 'night',
 'ninja',
 'no',
 'no background',
 'no bg',
 'nope',
 'norwegian',
 'norwegian forest cat',
 'nose',
 'nyan',
 'nyancat',
 'nyancat-gif',
 'obese',
 'ocean',
 'oden',
 'office',
 'old',
 'omg',
 'ominous',
 'on back',
 'on the piano',
 'one sock',
 'ooooo',
 'open',
 'open_mouth',
 'orange',
 'orange cat',
 'oriental',
 'outdoor',
 'outside',
 'ovni',
 'pain',
 'pair',
 'pan',
 'pancakes',
 'parents',
 'party',
 'pastic',
 'patched tabby',
 'patoka',
 'paw',
 'paw up',
 'paws',
 'pc',
 'pebba',
 'peekaboo',
 'peeking',
 'pencil',
 'peppa',
 'pepper',
 'persian',
 'persian cat',
 'petting',
 'photoshop',
 'piano',
 'pic',
 'pierced',
 'pillow',
 'pingu',
 'pink',
 'pino',
 'pippin',
 'plane',
 'plate',
 'play',
 'playful',
 'playing',
 'please',
 'pleased',
 'pleasing',
 'plinK',
 'plot',
 'plushie',
 'poptart',
 'portrait-worthy',
 'pose',
 'posing',
 'praise',
 'pretty',
 'printable',
 'professional',
 'programmer',
 'proud',
 'psychedelic',
 'puffy',
 'pumpkin',
 'punch',
 'puppy',
 'purple',
 'pussy',
 'pyret',
 'quality',
 'qwerty',
 'radical',
 'ragamuffin',
 'ragdoll',
 'rainbow',
 'random',
 'reaction',
 'reading',
 'record player',
 'red',
 'regal',
 'relax',
 'relaxed',
 'relaxing',
 'rest',
 'resting',
 'retard',
 'rich',
 'roaring',
 'roll',
 'rolling',
 'round',
 'round_face',
 'router',
 'rude',
 'running',
 'ruri',
 'russia',
 'russian blue',
 'ryes closed',
 'sad',
 'sad cat',
 'sad catto',
 'samurai',
 'santa',
 'sara',
 'sassy',
 'sat',
 'sauna cat',
 'savannah',
 'scared',
 'schmeckelz',
 'school',
 'school cat',
 'schottish',
 'scott',
 'scream',
 'screaming',
 'screams',
 'screm',
 'seeya!',
 'selfie',
 'serious',
 'serious face cat',
 'several',
 'shark',
 'shirt',
 'shit',
 'shnooze',
 'shocked',
 'shoe',
 'shoes',
 'short-haired',
 'shorthair',
 'shorthair cat',
 'shoxifykit',
 'shrek_ears',
 'shrimp',
 'siam',
 'siames',
 'siames tabby point',
 'siamese',
 'siberian',
 'siblings',
 'side view',
 'sideways',
 'sigma',
 'silly',
 'silver',
 'sing',
 'sisters',
 'sit',
 'sitting',
 'sitting at a stair',
 'sitting up',
 'slap',
 'sleep',
 'sleeping',
 'sleepy',
 'sleepy cat',
 'slick',
 'slide',
 'slip',
 'slow motion',
 'sluggish',
 'smack',
 'small',
 'small cat',
 'smart',
 'smile',
 'smirk',
 'smoking',
 'smol',
 'smug',
 'sniffing',
 'snoot',
 'snow',
 'snowshoe',
 'sock',
 'soda',
 'sofa',
 'soft',
 'soggy',
 'some',
 'soon',
 'sound',
 'space',
 'spaghetti',
 'speaking',
 'sphinx',
 'sphynx',
 'spicy',
 'spin',
 'spiral',
 'spooked',
 'spoon',
 'spots',
 'spotted',
 'spy',
 'square',
 'squeezed',
 'squint',
 'stack',
 'stair',
 'staline',
 'standardissue',
 'standing',
 'star',
 'star wars',
 'stare',
 'staring',
 'startled',
 'statue',
 'stealing',
 'stick',
 'stip',
 'store',
 'strange',
 'straw',
 'strawberry',
 'strech',
 'stretch',
 'stretched',
 'stretching',
 'stripe',
 'stripes',
 'strong',
 'stuck',
 'stupid',
 'style',
 'stylish',
 'suicide',
 ...]

In [46]:
df2 = pd.json_normalize(data)

df2

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1163 rows x 0 columns]